### ISSUE TITLE
App Crash on second open of app

### ISSUE THREAD

**Issue by charlesxu27** [FlyTrackers/FlyTrackers#35]
Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
CoreSimulator 783.5 - Device: iPhone 11 (EF4C3139-B464-405D-A565-6522B7D06722) - Runtime: iOS 15.2 (19C51) - DeviceType: iPhone 11
abort() called
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: ''applicationId' should not be nil.'
terminating with uncaught exception of type NSException

**Comment by GPropersi** [comment]
The app could not read the environment variables after closing and reopening the App. This meant Parse could no longer initialize with the API_KEY and CLIENT_ID needed, since it couldn't access them in the environment variables. I 

Fixed this by setting the values in UserDefaults to the environment variables. Insecure and we need to implement this with the KeyChain, but I couldn't spend the time to figure out how to use the KeyChain...

Pushed to the SettingsScreen branch.
